clinical_cases = {
    "case_1": {
        "name": "John Doe",
        "age": 45,
        "gender": "male",
        "symptoms": ["fever", "abdominal pain", "nausea"],
        "history": "type 2 diabetes",
        "diagnosis": "appendicitis",
        "emotions": "anxious and in pain",
        "pain_level": "high",
    },
    "case_2": {
        "name": "Jane Smith",
        "age": 30,
        "gender": "female",
        "symptoms": ["cough", "sore throat", "fatigue"],
        "history": "none",
        "diagnosis": "common cold",
        "emotions": "tired",
        "pain_level": "low",
    },
    "case_3": {
        "name": "Michael Johnson",
        "age": 60,
        "gender": "male",
        "symptoms": ["chest pain", "shortness of breath"],
        "history": "hypertension",
        "diagnosis": "myocardial infarction",
        "emotions": "fearful",
        "pain_level": "very high",
    },
    "case_4": {
        "name": "Emily Davis",
        "age": 25,
        "gender": "female",
        "symptoms": ["headache", "blurred vision"],
        "history": "migraine",
        "diagnosis": "migraine",
        "emotions": "irritated",
        "pain_level": "medium",
    },
    "case_5": {
        "name": "Robert Brown",
        "age": 50,
        "gender": "male",
        "symptoms": ["joint pain", "stiffness"],
        "history": "arthritis",
        "diagnosis": "osteoarthritis",
        "emotions": "frustrated",
        "pain_level": "medium",
    },
    
    "case_6": {
        "name": "Laura Wilson",
        "age": 40,
        "gender": "female",
        "symptoms": ["rash", "itchiness"],
        "history": "eczema",
        "diagnosis": "allergic reaction",
        "emotions": "uncomfortable",
        "pain_level": "low",
    },
    "case_7": {
        "name": "James Taylor",
        "age": 35,
        "gender": "male",
        "symptoms": ["back pain", "numbness"],
        "history": "disc herniation",
        "diagnosis": "sciatica",
        "emotions": "distressed",
        "pain_level": "high",
    },
    "case_8": {
        "name": "Olivia Martinez",
        "age": 28,
        "gender": "female",
        "symptoms": ["pelvic pain", "heavy bleeding"],
        "history": "none",
        "diagnosis": "endometriosis",
        "emotions": "worried",
        "pain_level": "high",
    },
    "case_9": {
        "name": "William Anderson",
        "age": 55,
        "gender": "male",
        "symptoms": ["fatigue", "weight gain"],
        "history": "none",
        "diagnosis": "hypothyroidism",
        "emotions": "lethargic",
        "pain_level": "low",
    },
    "case_10": {
        "name": "Sophia Thomas",
        "age": 22,
        "gender": "female",
        "symptoms": ["sneezing", "runny nose"],
        "history": "allergies",
        "diagnosis": "allergic rhinitis",
        "emotions": "bothered",
        "pain_level": "low",
    },
    
}
